name: Create PlantUML Images

on:
  push:
    paths:
      - docs/erd/*.puml #eg. docs/sequence-diagrams/*.puml  

jobs:
  build:
    runs-on: macos-11.0
    steps:
      #git checkout
      - uses: actions/checkout@v2
      #PlantUMLのパッケージインストール
      - name: Install packages
        run: |
          brew install plantuml
      #画像生成（最後のlsはGitActionのコンソール上で結果確認するため）
      - name: Create Images
        run: |
          cd ./docs
          for puml in `ls -a *.puml`
          do
            cat ./${puml} | plantuml -tsvg -p > ./${puml%.*}.svg
          done
          ls -l
      #git commit & git push
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: 'Create image files by GitHub Action(create-plantuml-images.yml).'
          add: './docs/*'
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # ここはおまじない的に必須